### ISSUE TITLE
No template for running query

### ISSUE THREAD

**Issue by ochicaud** [atifaziz/LinqPadless#37] opened 2019-10-10 09:07 UTC
Hello,

first try with 2.0 alpha. I just do a lpless "my file.linq"  an get a "No template for running query"

What does it mean ?

thanks

**Comment by atifaziz** [comment] 2019-10-10 09:30
Have a look at #27.

**Comment by atifaziz** [comment] 2019-10-11 13:57
Closing as duplicate of #27.

**Closed as completed by atifaziz** 2019-10-11 13:57 UTC
Labels: duplicate
